from us import states

states_abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

state_to_code_dict = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

code_to_state_dict = dict(map(reversed, state_to_code_dict.items()))

state_names = {key:code_to_state_dict[key] for key in states_abb}

country_list = [
    "Albania",
    "Argentina",
    "Australia",
    "Austria",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Bolivia",
    "Bulgaria",
    "Canada",
    "Chile",
    "Colombia",
    "CostaRica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "CzechRepublic",
    "Denmark",
    "DominicanRepublic",
    "Ecuador",
    "ElSalvador",
    "Estonia",
    "Ethiopia",
    "Finland",
    "France",
    "Germany",
    "Ghana",
    "Greece",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Malta",
    "Mexico",
    "Morocco",
    "Mozambique",
    "Nepal",
    "Netherlands",
    "NewZealand",
    "Nigeria",
    "NorthMacedonia",
    "Norway",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "SaudiArabia",
    "Senegal",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "SouthAfrica",
    "SouthKorea",
    "Spain",
    "SriLanka",
    "Sweden",
    "Switzerland",
    "Thailand",
    "Togo",
    "Tunisia",
    "Turkey",
    "UAE",
    "UK",
    "Ukraine",
    "Uruguay",
    "USA",
    "Zambia"
]

code_to_fips_dict = {
    "AL" : states.AL.fips,
    "AK" : states.AK.fips,
    "AZ" : states.AZ.fips,
    "AR" : states.AR.fips,
    "CA" : states.CA.fips,
    "CO" : states.CO.fips,
    "CT" : states.CT.fips,
    "DC" : states.DC.fips,
    "DE" : states.DE.fips,
    "FL" : states.FL.fips,
    "GA" : states.GA.fips,
    "HI" : states.HI.fips,
    "ID" : states.ID.fips,
    "IL" : states.IL.fips,
    "IN" : states.IN.fips,
    "IA" : states.IA.fips,
    "KS" : states.KS.fips,
    "KY" : states.KY.fips,
    "LA" : states.LA.fips,
    "ME" : states.ME.fips,
    "MD" : states.MD.fips,
    "MA" : states.MA.fips,
    "MI" : states.MI.fips,
    "MN" : states.MN.fips,
    "MS" : states.MS.fips,
    "MO" : states.MO.fips,
    "MT" : states.MT.fips,
    "NE" : states.NE.fips,
    "NV" : states.NV.fips,
    "NH" : states.NH.fips,
    "NJ" : states.NJ.fips,
    "NM" : states.NM.fips,
    "NY" : states.NY.fips,
    "NC" : states.NC.fips,
    "ND" : states.ND.fips,
    "OH" : states.OH.fips,
    "OK" : states.OK.fips,
    "OR" : states.OR.fips,
    "PA" : states.PA.fips,
    "RI" : states.RI.fips,
    "SC" : states.SC.fips,
    "SD" : states.SD.fips,
    "TN" : states.TN.fips,
    "TX" : states.TX.fips,
    "UT" : states.UT.fips,
    "VT" : states.VT.fips,
    "VA" : states.VA.fips,
    "WA" : states.WA.fips,
    "WV" : states.WV.fips,
    "WI" : states.WI.fips,
    "WY" : states.WY.fips
}


fips_to_code_dict = dict(map(reversed, code_to_fips_dict.items()))

fips_int_to_code_dict = {int(k):v for k,v in fips_to_code_dict.items()}

def generate_code_fips_file():
    with open('state_fips.txt', 'w') as outfile:
        for key in states_abb:
            outfile.write(f'\"{key}\" : states.{key}.fips,\n')

def generate_code_name_file():
    with open('state_names.txt','w') as outfile:
        for key in states_abb:
            outfile.write(f'{code_to_state_dict[key]}, ')

def main():
    generate_code_name_file()
    generate_code_fips_file()

if __name__ == "__main__":
    main()